version: '3.3'

services:

  wordpress_db:
    container_name: wordpress_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    container_name: wordpress
    depends_on:
      - wordpress_db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      SPRINGBOT_WOO_ETL: woo_etl:9000
      SPRINGBOT_ASSETS_DOMAIN: www_app:3000
      SPRINGBOT_APP_URL: www_app:3000
    volumes:
      - .:/var/www/html/wp-content/plugins/woocommerce-springbot


